# Generated by Django 5.0.2 on 2024-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_cursos_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='imagenes',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='id_curso',
            field=models.TextField(max_length=15),
        ),
    ]
