# Generated by Django 5.0.2 on 2024-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_cursos_imagenes_alter_cursos_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagenes',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
