# Generated by Django 5.0.2 on 2024-05-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_remove_cursos_imagenes_cursos_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='curso',
            new_name='imagen',
        ),
    ]
