# Generated by Django 5.0.2 on 2024-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_rename_curso_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
